# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PubConf
email: hello@pubconf.io
description: >
  Rapid-fire funny talks, musical acts, and comedy stunts from amazing developers. At the pub.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pubconf.io" # the base hostname & protocol for your site
image: "/assets/images/logo-horiz-dark.png"

# Generic Google Analytics Property. May be overridden by events.
UA: "UA-68386201-1"

newsletter_signup: "http://pubconf.us11.list-manage1.com/subscribe?u=33d7399517a3ee3a5e9b679f7&id=05e06dc18c"

googleplus_username: +pubconfio
facebook_username: pubconf
twitter_username: pubconf

# Build settings
markdown: kramdown
gems:
  - jekyll-assets

exclude:
  - "Gemfile*"

assets:
  sources:
    - _assets/vendor/bootstrap/js
    - _assets/vendor/jquery
    - _assets/vendor/magnific
